name: 'Just Simple Greetings'
description: 'Simple Action Greetings to Someone'
inputs:
  who-to-great:
    description: 'Who to Great'
    required: true
    default: 'World'
branding:
  icon: 'heart'
  color: 'yellow'
runs:
  using: 'docker'
  image:  'Dockerfile'
  args:
    - ${{ inputs.who-to-great }}